

[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
local replace_sound = SMODS.Sound.replace_sounds[desired_track]
'''
position = "at"
payload = '''
local replace_sound = Penumbra.GetReplaceMusic(desired_track)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''
if self.config.colour[4] > 0.01 then
'''
position = "before"
payload = '''
if not self.config.colour then self.config.colour = {1,0,0,1} end
'''
match_indent = true
